<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: miércoles, 19 de junio de 2024 22:10:11</msg><msg code="0" type="0">Empieza el geoproceso</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\juaco\OneDrive\Documentos\ArcGIS\Packages\DAG_1s2024_L_TRABAJO_1_PARTE_2_JBV_d59d9f\p30\dag_1s2024_l_trabajo_1_parte_2_jbv.gdb\indiresg.py", line 33, in &lt;module&gt;
    arcpy.management.CalculateField(fcIn6, nombre_campo, "((0.2 * 1 / !MEAN!) + (0.1 * !DENS_POB_MANZ!) + (0.1 * 1 / (!DIST_VM! + 0.01)) + (0.1 * !Join_Count!) + (0.1 * !DIST_RH!) + (0.4 * !DIST_BC!))/(1000 * 3.772302)", field_type="DOUBLE")
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 6187, in CalculateField
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\management.py", line 6184, in CalculateField
    retval = convertArcObjectToPythonObject(gp.CalculateField_management(*gp_fixargs((in_table, field, expression, expression_type, code_block, field_type, enforce_domains), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: ERROR 000539: Invalid field MEAN
Failed to execute (CalculateField).

</msg><msg code="0" type="0">Failed script 6.1.- CALCULATE FIELD INDICE DE RIESGO...</msg><msg code="-2147467259" type="100">Failed to execute (INDRIESG).</msg><msg code="0" type="3">Failed at miércoles, 19 de junio de 2024 22:10:21 (Elapsed Time: 9.53 seconds)</msg></messages>