<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: jueves, 20 de junio de 2024 1:47:56</msg><msg code="0" type="0">Empieza el geoproceso</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\juaco\OneDrive\Documentos\ArcGIS\Packages\DAG_1s2024_L_TRABAJO_1_PARTE_2_JBV_d59d9f\p30\dag_1s2024_l_trabajo_1_parte_2_jbv.gdb\paso 3.py", line 33, in &lt;module&gt;
    arcpy.analysis.SpatialJoin(fcIn4, join_features, fcOut)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py", line 797, in SpatialJoin
    raise e
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\analysis.py", line 794, in SpatialJoin
    retval = convertArcObjectToPythonObject(gp.SpatialJoin_analysis(*gp_fixargs((target_features, join_features, out_feature_class, join_operation, join_type, field_mapping, match_option, search_radius, distance_field_name), True)))
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\geoprocessing\_base.py", line 512, in &lt;lambda&gt;
    return lambda *args: val(*gp_fixargs(args, True))
arcgisscripting.ExecuteError: Failed to execute. Parameters are not valid.
ERROR 000354: The name contains invalid characters
Failed to execute (SpatialJoin).

</msg><msg code="0" type="0">Failed script 2.1.- SPATIAL JOIN DE ESTABLECIMIENTOS DE SALUD POR MANZANAS...</msg><msg code="-2147467259" type="100">Failed to execute (ESTPORMANZANA).</msg><msg code="0" type="3">Failed at jueves, 20 de junio de 2024 1:48:00 (Elapsed Time: 4.92 seconds)</msg></messages>